### ISSUE TITLE
Compilation Error on Ubuntu 20.04 Noetic

### ISSUE THREAD

**Issue by vaibhavkad-peppermint** [ZhamaoDra/kinodynamic_frontend#1]
Please add install_dependencies.sh

**Comment by ZamesNg** [comment]
What is the error? 
The project only depend on NLopt and Eigen3. you can search the google for install cmd.
And the error might cause by my mistake upload, I just fix it, you can download the repo again and compile it.

**Comment by vaibhavkad-peppermint** [comment]
One of the few errors occurred during compilation
![image](https://user-images.githubusercontent.com/87687973/161975691-bc3df9a4-0079-477e-8e41-18fadc2cca47.png)

**Comment by ZamesNg** [comment]
this error is caused by c++ compile standra.
try add `set(CMAKE_CXX_STANDARD 14)`  to your CMakeList.txt

**Comment by vaibhavkad-peppermint** [comment]
Adding Cmake standard 14 worked !!! Thanks a lot
