### ISSUE TITLE
关于calcOptimalTrajWithFullState_和calcOptimalTrajWithPartialState_

### ISSUE THREAD

**Issue by liangjunwu98** [ZhamaoDra/kinodynamic_frontend#2]
请问这两个函数里的计算方法有相关的推导资料吗

**Comment by ZamesNg** [comment]
可以参考高飞老师在深蓝学院上的课程。或者搜索一下OBVP（optimal bundary value problem）问题的解法。

**Comment by liangjunwu98** [comment]
已找到参考《A computationally effcient motion primitive for quadrocopter trajectory generation》

**Comment by liangjunwu98** [comment]
> 可以参考高飞老师在深蓝学院上的课程。或者搜索一下OBVP（optimal bundary value problem）问题的解法。

您好，我想再问一下，这两个函数里计算了一个m矩阵，通过计算其特征值得到最有时间，这个方法有相关的论文吗？在高飞老师的课上好像没有讲。谢谢啦

**Comment by liangjunwu98** [comment]
> 可以参考高飞老师在深蓝学院上的课程。或者搜索一下OBVP（optimal bundary value problem）问题的解法。

您好，我想再问一下，这两个函数里计算了一个m矩阵，通过计算其特征值得到最有时间，这个方法相关的参考吗？在高飞老师的课上好像没有讲。谢谢啦

**Comment by liangjunwu98** [comment]
> 可以参考高飞老师在深蓝学院上的课程。或者搜索一下OBVP（optimal bundary value problem）问题的解法。

您好，我想再问一下，这两个函数里计算了一个m矩阵，通过计算其特征值得到两个点之间的运动时间，这个方法相关的参考吗？在高飞老师的课上好像没有讲。谢谢啦

**Comment by ZamesNg** [comment]
> 

高飞老师的课应该是有讲这部分的。可能是在课后练习解答里面。我可以大概说一下思路：
把最优解带入到cost function里，会得到一个只和变量T有关的多项式。那么最优的T就可以通过令cost function的导数为0得到。多项式的导数还是一个多项式，那么问题就变成了多项式求根。
代码里的m矩阵就是根据需要求根的多项式构造来的，其特征值为原多项式的根。具体可以搜一下去MATLAB是怎么解多项式的。

**Comment by liangjunwu98** [comment]
> > 
> 
> 高飞老师的课应该是有讲这部分的。可能是在课后练习解答里面。我可以大概说一下思路： 把最优解带入到cost function里，会得到一个只和变量T有关的多项式。那么最优的T就可以通过令cost function的导数为0得到。多项式的导数还是一个多项式，那么问题就变成了多项式求根。 代码里的m矩阵就是根据需要求根的多项式构造来的，其特征值为原多项式的根。具体可以搜一下去MATLAB是怎么解多项式的。

谢谢啦。把alpha、beta、gamma代进去之后，J的表达式好复杂，求偏导也太难了(ಥ_ಥ)
